// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aerosystems/adapter-service/internal/config"
	"github.com/aerosystems/adapter-service/internal/http"
	"github.com/aerosystems/adapter-service/internal/infrastructure/rest"
	"github.com/aerosystems/adapter-service/internal/repository/verifire"
	"github.com/aerosystems/adapter-service/internal/usecases"
	"github.com/aerosystems/adapter-service/pkg/logger"
	"github.com/aerosystems/adapter-service/pkg/oauth"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

//go:generate wire
func InitApp() *App {
	logger := ProvideLogger()
	logrusLogger := ProvideLogrusLogger(logger)
	config := ProvideConfig()
	api := ProvideVerifireApi(config)
	proxyUsecase := ProvideProxyUsecase(api)
	inspectHandler := ProvideInspectHandler(proxyUsecase)
	accessTokenService := ProvideAccessTokenService(config)
	server := ProvideHttpServer(logrusLogger, inspectHandler, accessTokenService)
	app := ProvideApp(logrusLogger, config, server)
	return app
}

func ProvideApp(log *logrus.Logger, cfg *config.Config, httpServer *HttpServer.Server) *App {
	app := NewApp(log, cfg, httpServer)
	return app
}

func ProvideLogger() *logger.Logger {
	loggerLogger := logger.NewLogger()
	return loggerLogger
}

func ProvideConfig() *config.Config {
	configConfig := config.NewConfig()
	return configConfig
}

func ProvideHttpServer(log *logrus.Logger, inspectHandler *rest.InspectHandler, tokenService HttpServer.TokenService) *HttpServer.Server {
	server := HttpServer.NewServer(log, inspectHandler, tokenService)
	return server
}

func ProvideInspectHandler(proxyUsecase rest.ProxyUsecase) *rest.InspectHandler {
	inspectHandler := rest.NewInspectHandler(proxyUsecase)
	return inspectHandler
}

func ProvideProxyUsecase(checkmailRepo usecases.VerifireRepository) *usecases.ProxyUsecase {
	proxyUsecase := usecases.NewProxyUsecase(checkmailRepo)
	return proxyUsecase
}

// wire.go:

func ProvideLogrusLogger(log *logger.Logger) *logrus.Logger {
	return log.Logger
}

func ProvideAccessTokenService(cfg *config.Config) *OAuthService.AccessTokenService {
	return OAuthService.NewAccessTokenService(cfg.AccessSecretProxy)
}

func ProvideVerifireApi(cfg *config.Config) *verifire.Api {
	return verifire.NewApi(cfg.VerifireBaseURL)
}
